### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by MariiaHuchko** [MariiaHuchko/pr4_2022#1]
Знайти найкраще фото в Інтернеті

**Comment by vikazagorbenska** [comment]
Вже шукаю

**Comment by vikazagorbenska** [comment]
![image](https://user-images.githubusercontent.com/117088245/199016191-5b83a79c-cd25-416d-99d7-de99cb0efd26.png)

**Comment by vikazagorbenska** [comment]
![image](https://user-images.githubusercontent.com/117088245/199016335-66227665-dda7-4cb8-b5cd-984231ca57e1.png)

**Comment by vikazagorbenska** [comment]
Зображення знайдено

**Comment by MariiaHuchko** [comment]
Зображення знайдено
